language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U -r requirements.txt
  - poetry install

script:
  - poetry run pytest
  - poetry run flake8
  - poetry run black --check . || false

deploy:
  provider: script
  script: poetry publish --build -u __token__ -p $PYPI_SECRET
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"
