language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U -r requirements.txt
  - poetry install

script:
  - pytest
  - flake8

before_deploy:
  - poetry config repositories.pypi $PYPI_URL __token__ -p $PYPI_SECRET
  - poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    branch: dev
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.7"
