language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U -r requirements.txt
  - poetry install
  - poetry config repositories.target $PYPI_URL

script:
  - pytest
  - flake8

deploy:
  provider: script
  script: poetry publish -r target -u __token__ -p $PYPI_SECRET --build
  password:
    secure: $PYPI_SECRET
  on:
    branch: master
    tags: true
