language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U -r requirements.txt
  - poetry install

script:
  - pytest
  - flake8

deploy:
  provider: script
  script: 
    - poetry config repositories.pypi $PYPI_URL
    - poetry publish -r pypi -u __token__ -p $PYPI_SECRET --build
  on:
    branch: dev
    tags: true
