language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U -r requirements.txt
  - poetry install

script:
  - pytest
  - flake8

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_SECRET
  server: "https://test.pypi.org/manage/account/"
  on:
    branch: master
    tags: true