language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U -r requirements.txt
  - poetry install

script:
  - pytest
  - flake8

before_deploy:
  - poetry config http-basic.pypi __token__ $PYPI_SECRET

deploy:
  provider: script
  script: poetry publish -r pypi --build
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION == 3.8"
